import { Geist, Geist_Mono, Kiwi_Maru } from 'next/font/google';
import React from 'react';

import type { webFontName } from '@team/theme';
import type { Metadata } from 'next';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// フォント名は @team/theme の webFontName と同期: Kiwi_Maru
// next/font/google は静的解析のため動的インポートができないため、
// フォント名を変更する場合は @team/theme と同時に更新すること
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const _fontNameCheck: typeof webFontName = 'Kiwi_Maru';

const kiwiMaru = Kiwi_Maru({
  weight: ['300', '400', '500'],
  variable: '--font-kiwi-maru',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${kiwiMaru.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
