name: 'Setup pnpm and Node.js'
description: 'Sets up pnpm and Node.js with caching'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '24.x'
  working-directory:
    description: 'Working directory for pnpm install'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pnpm install --frozen-lockfile
