name: 'Setup Go'
description: 'Sets up Go with caching and downloads dependencies'

inputs:
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.25'
  working-directory:
    description: 'Working directory for go mod download'
    required: false
    default: 'apps/backend'

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ inputs.go-version }}
        cache-dependency-path: ${{ inputs.working-directory }}/go.sum

    - name: Download dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: go mod download
