name: 'Setup Expo'
description: 'Sets up pnpm, Node.js, and Expo CLI with caching'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '24.x'
  expo-version:
    description: 'Expo CLI version to use'
    required: false
    default: 'latest'
  expo-token:
    description: 'Expo token for authentication'
    required: true
  working-directory:
    description: 'Working directory for installation'
    required: false
    default: 'apps/mobile'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Ensure pnpm cache dirs
      shell: bash
      run: |
        mkdir -p "$HOME/.pnpm-store"
        mkdir -p "$HOME/.local/share/pnpm"

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pnpm install --frozen-lockfile

    - name: Setup Expo CLI
      uses: expo/expo-github-action@v8
      with:
        expo-version: ${{ inputs.expo-version }}
        token: ${{ inputs.expo-token }}
