name: 'Setup Expo'
description: 'Sets up pnpm, Node.js, and Expo CLI with caching'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '24.x'
  expo-version:
    description: 'Expo CLI version to use'
    required: false
    default: 'latest'
  expo-token:
    description: 'Expo token for authentication'
    required: true
  working-directory:
    description: 'Working directory for installation'
    required: false
    default: 'apps/mobile'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm and Node.js
      uses: ./.github/actions/pnpm-setup
      with:
        node-version: ${{ inputs.node-version }}
        working-directory: ${{ inputs.working-directory }}

    - name: Setup Expo CLI
      uses: expo/expo-github-action@v8
      with:
        expo-version: ${{ inputs.expo-version }}
        token: ${{ inputs.expo-token }}
